/**
 * geo.codes
 * The alpha version of the [https://geo.codes](https://geo.codes) API service. See API documentation [here](https://geo.codes/docs/api). 10,000 free queries per month.
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * Contact: help@geo.codes
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* Auth service.
* @module GeoCodes/api/AuthApi
* @version 1.0.0-alpha
*/
export default class AuthApi {

    /**
    * Constructs a new AuthApi. 
    * @alias module:GeoCodes/api/AuthApi
    * @class
    * @param {module:GeoCodes/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:GeoCodes/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Ping function that tests the API Key
     * **Description**  An endpoint that always responds with the string `authorized!` when authentication works. This can be used as a check that the authentication on a request is valid.  Please include your key on the `Authorization` header or the query parameter `api_key`  **No account required**  This endpoint requires an account to be accessed, but does not count as a lookup. Requests may still be rejected due to rate limiting by any facet (account, IP, etc), in order to preserve the health of the service.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link String} and HTTP response
     */
    v1TestWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyHeaderAuth', 'ApiKeyURLAuth'];
      let contentTypes = [];
      let accepts = ['text/plain'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/v1/test', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Ping function that tests the API Key
     * **Description**  An endpoint that always responds with the string `authorized!` when authentication works. This can be used as a check that the authentication on a request is valid.  Please include your key on the `Authorization` header or the query parameter `api_key`  **No account required**  This endpoint requires an account to be accessed, but does not count as a lookup. Requests may still be rejected due to rate limiting by any facet (account, IP, etc), in order to preserve the health of the service.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link String}
     */
    v1Test() {
      return this.v1TestWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
