/**
 * geo.codes
 * The alpha version of the [https://geo.codes](https://geo.codes) API service. See API documentation [here](https://geo.codes/docs/api). 10,000 free queries per month.
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * Contact: help@geo.codes
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* Default service.
* @module GeoCodes/api/DefaultApi
* @version 1.0.0-alpha
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:GeoCodes/api/DefaultApi
    * @class
    * @param {module:GeoCodes/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:GeoCodes/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Ping the service without credentials
     * An endpoint that always responds with the string \"pong\". This can be used as a health check.<br><br>  This endpoint does not require an account to be accessed, and does not count as a lookup. Requests may still be rejected due to rate limiting to preserve the health of the service.  Alpha of Version 1 of the geo.codes API. Once V1 is stabilized, routes under `/v1` are guaranteed to follow semver-style backwards compatibility guarantees.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link String} and HTTP response
     */
    pingWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/plain'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/ping', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Ping the service without credentials
     * An endpoint that always responds with the string \"pong\". This can be used as a health check.<br><br>  This endpoint does not require an account to be accessed, and does not count as a lookup. Requests may still be rejected due to rate limiting to preserve the health of the service.  Alpha of Version 1 of the geo.codes API. Once V1 is stabilized, routes under `/v1` are guaranteed to follow semver-style backwards compatibility guarantees.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link String}
     */
    ping() {
      return this.pingWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
