/**
 * geo.codes
 * The alpha version of the [https://geo.codes](https://geo.codes) API service. See API documentation [here](https://geo.codes/docs/api). 10,000 free queries per month.
 *
 * The version of the OpenAPI document: 1.0.0-alpha
 * Contact: help@geo.codes
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Geocoding from '../model/Geocoding';
import ReverseZIPCode from '../model/ReverseZIPCode';
import ZIPCode from '../model/ZIPCode';

/**
* Geocode service.
* @module GeoCodes/api/GeocodeApi
* @version 1.0.0-alpha
*/
export default class GeocodeApi {

    /**
    * Constructs a new GeocodeApi. 
    * @alias module:GeoCodes/api/GeocodeApi
    * @class
    * @param {module:GeoCodes/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:GeoCodes/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Geocode an unstructured address string
     * **Description**<br><br>  Geocode a single address. This parses the input address and matches it against our records to produce the geocoded result.  This does a best-attempt to geocode the given address in the face of human errors in the input data. This can be the wrong city (\"New York City\" instead of \"New York\") a missing postal code, a misspelled street name, house numbers that don't exist, etc.  As more corrections are needed, the certainty in the result drops. This can be tuned with a minimum certainty parameter. If our confidence in the result is less than the minimum certainty, it will not be returned. The default is 30. 30 was chosen to be robust against unclean data without returning results that are unlikely to be true. We don't recommend setting this parameter above 90 because exact matching is too restrictive for the mistakes that people typically make when writing addresses -- even people writing their own addresses will make mistakes that are never corrected.  **Lookup cost**  This query requires an account. Please sign up at https://geo.codes/signup and get your API key at https://geo.codes/account/api  One query counts as one lookup. It only costs a query if it returns data. If you have exceeded your account quota, the request will not succeed.
     * @param {String} q The unstructured address to geocode. Expected to be roughly the format that is used by the USPS to deliver mail.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.minConfidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don't recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:GeoCodes/model/Geocoding} and HTTP response
     */
    v1AddressGeocodeWithHttpInfo(q, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'q' is set
      if (q === undefined || q === null) {
        throw new Error("Missing the required parameter 'q' when calling v1AddressGeocode");
      }

      let pathParams = {
      };
      let queryParams = {
        'q': q,
        'min_confidence': opts['minConfidence']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyHeaderAuth', 'ApiKeyURLAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Geocoding;
      return this.apiClient.callApi(
        '/v1/address/geocode', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Geocode an unstructured address string
     * **Description**<br><br>  Geocode a single address. This parses the input address and matches it against our records to produce the geocoded result.  This does a best-attempt to geocode the given address in the face of human errors in the input data. This can be the wrong city (\"New York City\" instead of \"New York\") a missing postal code, a misspelled street name, house numbers that don't exist, etc.  As more corrections are needed, the certainty in the result drops. This can be tuned with a minimum certainty parameter. If our confidence in the result is less than the minimum certainty, it will not be returned. The default is 30. 30 was chosen to be robust against unclean data without returning results that are unlikely to be true. We don't recommend setting this parameter above 90 because exact matching is too restrictive for the mistakes that people typically make when writing addresses -- even people writing their own addresses will make mistakes that are never corrected.  **Lookup cost**  This query requires an account. Please sign up at https://geo.codes/signup and get your API key at https://geo.codes/account/api  One query counts as one lookup. It only costs a query if it returns data. If you have exceeded your account quota, the request will not succeed.
     * @param {String} q The unstructured address to geocode. Expected to be roughly the format that is used by the USPS to deliver mail.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.minConfidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don't recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:GeoCodes/model/Geocoding}
     */
    v1AddressGeocode(q, opts) {
      return this.v1AddressGeocodeWithHttpInfo(q, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Convert a coordinate to a ZIP Code
     * **Description**<br>  Look up a single ZIP Code from the given latitude and longitude.  This performs a lookup based on US Census \"ZIP Code Tabulation Areas.\" These areas are calculated by the US Census based on the most common ZIP Codes within different US Census blocks. This is necessary because in practice, ZIP Codes are not defined by areas but are defined as collections of addresses. They correspond loosely to areas, but not exactly. To get an accurate ZIP Code for an address, see the geocoding endpoints.  For more information on ZIP Code tabulation areas and why ZIP Codes cannot be accurately represented by areas, [click here](https://geo.codes/resources/articles/complete-guide-to-zip-codes#what-are-zip-code-tabulation-areas).  They have the following limitations: - ZIP Code Tabulation Areas do not have full coverage of the land mass of the United States. This only matters in remote areas without deliverable addresses; in practice this is fine. In these cases, the API will return the closest tabulation area unless the ` + \"`strict`\" + ` parameter is provided. - Addresses within a ZIP Code Tabulation Area might have different ZIP Codes. Geocoding an address is the only way to get a perfect ZIP Code. - The PlusFour field on the return value will always be empty.  **Lookup cost**<br>  This query requires an account. Please sign up at https://geo.codes/signup and get your API key at https://geo.codes/account/api  One query counts as one lookup. It only costs a query if it returns data. If you have exceeded your account quota, the request will not succeed.
     * @param {Number} latitude The latitude of the query
     * @param {Number} longitude The longitude of the query
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.strict If true, will only return a result if the given point is within a zip code tabulation area, and will not return the closest one.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:GeoCodes/model/ReverseZIPCode} and HTTP response
     */
    v1AddressReverseZipCodeWithHttpInfo(latitude, longitude, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'latitude' is set
      if (latitude === undefined || latitude === null) {
        throw new Error("Missing the required parameter 'latitude' when calling v1AddressReverseZipCode");
      }
      // verify the required parameter 'longitude' is set
      if (longitude === undefined || longitude === null) {
        throw new Error("Missing the required parameter 'longitude' when calling v1AddressReverseZipCode");
      }

      let pathParams = {
      };
      let queryParams = {
        'latitude': latitude,
        'longitude': longitude,
        'strict': opts['strict']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyHeaderAuth', 'ApiKeyURLAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ReverseZIPCode;
      return this.apiClient.callApi(
        '/v1/address/reverse_zip_code', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Convert a coordinate to a ZIP Code
     * **Description**<br>  Look up a single ZIP Code from the given latitude and longitude.  This performs a lookup based on US Census \"ZIP Code Tabulation Areas.\" These areas are calculated by the US Census based on the most common ZIP Codes within different US Census blocks. This is necessary because in practice, ZIP Codes are not defined by areas but are defined as collections of addresses. They correspond loosely to areas, but not exactly. To get an accurate ZIP Code for an address, see the geocoding endpoints.  For more information on ZIP Code tabulation areas and why ZIP Codes cannot be accurately represented by areas, [click here](https://geo.codes/resources/articles/complete-guide-to-zip-codes#what-are-zip-code-tabulation-areas).  They have the following limitations: - ZIP Code Tabulation Areas do not have full coverage of the land mass of the United States. This only matters in remote areas without deliverable addresses; in practice this is fine. In these cases, the API will return the closest tabulation area unless the ` + \"`strict`\" + ` parameter is provided. - Addresses within a ZIP Code Tabulation Area might have different ZIP Codes. Geocoding an address is the only way to get a perfect ZIP Code. - The PlusFour field on the return value will always be empty.  **Lookup cost**<br>  This query requires an account. Please sign up at https://geo.codes/signup and get your API key at https://geo.codes/account/api  One query counts as one lookup. It only costs a query if it returns data. If you have exceeded your account quota, the request will not succeed.
     * @param {Number} latitude The latitude of the query
     * @param {Number} longitude The longitude of the query
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.strict If true, will only return a result if the given point is within a zip code tabulation area, and will not return the closest one.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:GeoCodes/model/ReverseZIPCode}
     */
    v1AddressReverseZipCode(latitude, longitude, opts) {
      return this.v1AddressReverseZipCodeWithHttpInfo(latitude, longitude, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Geocode structured addresses
     * **Description**<br>  Geocode a single structured address. This takes address components (street, city, state, etc) and matches it against our records to produce the geocoded result.  This does a best-attempt to geocode the given address in the face of human errors in the input data. This can be the wrong city (\"New York City\" instead of \"New York\") a missing postal code, a misspelled street name, house numbers that don't exist, etc.  As more corrections are needed, the certainty in the result drops. This can be tuned with a minimum certainty parameter. If our confidence in the result is less than the minimum certainty, it will not be returned. The default is 30%. 30% was chosen to be robust against unclean data without returning results that are unlikely to be true. We don't recommend setting this parameter above 90% because exact matching is too restrictive for the mistakes that people typically make when writing addresses -- even people writing their own addresses will make mistakes that are never corrected because they Just Work.  **Lookup cost**<br>  This query requires an account. Please sign up at https://geo.codes/signup and get your API key at https://geo.codes/account/api  One query counts as one lookup. It only costs a query if it returns data. If you have exceeded your account quota, the request will not succeed.
     * @param {String} streetAddress The street address line, including the number and street type.
     * @param {Object} opts Optional parameters
     * @param {String} opts.city The city. Not required, but it's highly recommended that you add either the city or postal_code fields.
     * @param {String} opts.state The state with the address. Not required, but it's highly recommended that you add the postal_code if the state is not present.
     * @param {String} opts.postalCode The postal code, for example, a ZIP code. Not required, but if this is not present, we recommend adding the city and the state for best results.
     * @param {Number} opts.minConfidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don't recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:GeoCodes/model/Geocoding} and HTTP response
     */
    v1AddressStructuredGeocodeWithHttpInfo(streetAddress, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'streetAddress' is set
      if (streetAddress === undefined || streetAddress === null) {
        throw new Error("Missing the required parameter 'streetAddress' when calling v1AddressStructuredGeocode");
      }

      let pathParams = {
      };
      let queryParams = {
        'street_address': streetAddress,
        'city': opts['city'],
        'state': opts['state'],
        'postal_code': opts['postalCode'],
        'min_confidence': opts['minConfidence']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyHeaderAuth', 'ApiKeyURLAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Geocoding;
      return this.apiClient.callApi(
        '/v1/address/structured_geocode', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Geocode structured addresses
     * **Description**<br>  Geocode a single structured address. This takes address components (street, city, state, etc) and matches it against our records to produce the geocoded result.  This does a best-attempt to geocode the given address in the face of human errors in the input data. This can be the wrong city (\"New York City\" instead of \"New York\") a missing postal code, a misspelled street name, house numbers that don't exist, etc.  As more corrections are needed, the certainty in the result drops. This can be tuned with a minimum certainty parameter. If our confidence in the result is less than the minimum certainty, it will not be returned. The default is 30%. 30% was chosen to be robust against unclean data without returning results that are unlikely to be true. We don't recommend setting this parameter above 90% because exact matching is too restrictive for the mistakes that people typically make when writing addresses -- even people writing their own addresses will make mistakes that are never corrected because they Just Work.  **Lookup cost**<br>  This query requires an account. Please sign up at https://geo.codes/signup and get your API key at https://geo.codes/account/api  One query counts as one lookup. It only costs a query if it returns data. If you have exceeded your account quota, the request will not succeed.
     * @param {String} streetAddress The street address line, including the number and street type.
     * @param {Object} opts Optional parameters
     * @param {String} opts.city The city. Not required, but it's highly recommended that you add either the city or postal_code fields.
     * @param {String} opts.state The state with the address. Not required, but it's highly recommended that you add the postal_code if the state is not present.
     * @param {String} opts.postalCode The postal code, for example, a ZIP code. Not required, but if this is not present, we recommend adding the city and the state for best results.
     * @param {Number} opts.minConfidence The minimum confidence in the results required to return an address, as a percentage between 0 and 100. Default: 30. To accept only exact data matches, choose 100. To be as permissive as possible, set it to 0. We don't recommend setting this higher than 90. It is very common for people to write their own addresses in ways that deviate from the exact match.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:GeoCodes/model/Geocoding}
     */
    v1AddressStructuredGeocode(streetAddress, opts) {
      return this.v1AddressStructuredGeocodeWithHttpInfo(streetAddress, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Convert a ZIP Code to a coordinate
     * **Description**<br>  Convert a single ZIP Code into a latitude and longitude.  By default, this returns a point that is guaranteed to be interior to the given ZIP Code. It may not necessarily be the centroid, because the centroid of some ZIP Codes do not fall within their borders (imagine a ZIP Code that is shaped like a crescent).  If a Plus-4 ZIP code is passed, only the first 5 digits will be used (i.e. the +4 will be ignored).  This performs a lookup based on US Census \"ZIP Code Tabulation Areas.\" These areas are calculated by the US Census based on the most common ZIP Codes within different US Census blocks. This is necessary because in practice, ZIP Codes are not defined by areas but are defined as collections of addresses. They correspond loosely to areas, but not exactly. To get an accurate ZIP Code for an address, see the geocoding endpoints.  For more information on ZIP Code tabulation areas and why ZIP Codes cannot be accurately represented by areas, [click here](https://geo.codes/resources/articles/complete-guide-to-zip-codes#what-are-zip-code-tabulation-areas).
     * @param {String} zipCode The ZIP Code of the query. Can be a ZIP Code or a ZIP+4 Code. If a +4 extension is passed, it will be ignored.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:GeoCodes/model/ZIPCode} and HTTP response
     */
    v1AddressZipCodeWithHttpInfo(zipCode) {
      let postBody = null;
      // verify the required parameter 'zipCode' is set
      if (zipCode === undefined || zipCode === null) {
        throw new Error("Missing the required parameter 'zipCode' when calling v1AddressZipCode");
      }

      let pathParams = {
      };
      let queryParams = {
        'zip_code': zipCode
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyHeaderAuth', 'ApiKeyURLAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ZIPCode;
      return this.apiClient.callApi(
        '/v1/address/zip_code', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Convert a ZIP Code to a coordinate
     * **Description**<br>  Convert a single ZIP Code into a latitude and longitude.  By default, this returns a point that is guaranteed to be interior to the given ZIP Code. It may not necessarily be the centroid, because the centroid of some ZIP Codes do not fall within their borders (imagine a ZIP Code that is shaped like a crescent).  If a Plus-4 ZIP code is passed, only the first 5 digits will be used (i.e. the +4 will be ignored).  This performs a lookup based on US Census \"ZIP Code Tabulation Areas.\" These areas are calculated by the US Census based on the most common ZIP Codes within different US Census blocks. This is necessary because in practice, ZIP Codes are not defined by areas but are defined as collections of addresses. They correspond loosely to areas, but not exactly. To get an accurate ZIP Code for an address, see the geocoding endpoints.  For more information on ZIP Code tabulation areas and why ZIP Codes cannot be accurately represented by areas, [click here](https://geo.codes/resources/articles/complete-guide-to-zip-codes#what-are-zip-code-tabulation-areas).
     * @param {String} zipCode The ZIP Code of the query. Can be a ZIP Code or a ZIP+4 Code. If a +4 extension is passed, it will be ignored.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:GeoCodes/model/ZIPCode}
     */
    v1AddressZipCode(zipCode) {
      return this.v1AddressZipCodeWithHttpInfo(zipCode)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
